steps:
  - name: 'maven:3.9.6-eclipse-temurin-17'
    entrypoint: bash
    args: ['-c', 'mvn clean package -DskipTests']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/arthasetu', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/arthasetu']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'arthasetu',
      '--image', 'gcr.io/$PROJECT_ID/arthasetu',
      '--region', 'asia-south1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

images:
  - gcr.io/$PROJECT_ID/arthasetu
#https://arthasetu-mw-282482783617.asia-south1.run.app